AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a Lambda custom resource for Cloudformation to search for and
  return latest AMI ID
Parameters:
  ParamS3Bucket:
    Description: The S3 Bucket that holds the lambda code
    Type: String
    Default: cloudformation-test2258
  ParamS3Key:
    Description: The S3 key for the lambda code zip file
    Type: String
    Default: lambda_function.zip
  LambdaVersion:
    Description: The S3 key for the lambda code zip file
    Type: String
    Default: 6oCat5X_noyIZZa.hfKCeOXM2uLutDjF

Resources:
  
  LambdaFunction:
    Type: AWS::Lambda::Function
  Environment:
    Variables:
      databaseName : lambdadb
    Properties:
      Code:
        S3Bucket:
          Ref: ParamS3Bucket
        S3Key:
          Ref: ParamS3Key
        S3ObjectVersion:
          Ref: LambdaVersion
      Description: Custom CloudFormation resoiurce to return the latest AMI with given
        search parameters
      FunctionName:
        Fn::Sub: Lamda-${AWS::StackName}
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::926559377299:role/AMI-Search-testnew25
      Runtime: nodejs12.x
      Timeout: 61
Outputs:
  LambdaFunctionARN:
    Description: The ARN of the lambda function
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
