AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a Lambda custom resource for Cloudformation to search for and
  return latest AMI ID
Resources:
  
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: ParamS3Bucket
        S3Key:
          Ref: ParamS3Key
      Description: Custom CloudFormation resoiurce to return the latest AMI with given
        search parameters
      FunctionName:
        Fn::Sub: Lamda-${AWS::StackName}
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::926559377299:role/AMI-Search-testnew25
      Runtime: nodejs12.x
      Timeout: 90
Outputs:
  LambdaFunctionARN:
    Description: The ARN of the lambda function
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
    Export:
      Name: test22
