AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a Lambda custom resource for Cloudformation to search for and
  return latest AMI ID
Parameters:
  ParamS3Bucket:
    Description: The S3 Bucket that holds the lambda code
    Type: String
    Default: 'us-east-22222222'
  ParamS3Key:
    Description: The S3 key for the lambda code zip file
    Type: String
    Default: 'lambda_function.zip'
Resources:
  
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: ParamS3Bucket
        S3Key:
          Ref: ParamS3Key
      Description: Custom CloudFormation resoiurce to return the latest AMI with given
        search parameters
      FunctionName:
        Fn::Sub: AMI-Search-${AWS::StackName}
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::260913995125:role/AMI-Search-testnew55
      Runtime: python3.9
      Timeout: 80
Outputs:
  LambdaFunctionARN:
    Description: The ARN of the lambda function
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
    Export:
      Name: test
