AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a Lambda custom resource for Cloudformation to search for and
  return latest AMI ID
Parameters:
  ParamS3Bucket:
    Description: The S3 Bucket that holds the lambda code
    Type: String
    Default: us-east-22222222
  ParamS3Key:
    Description: The S3 key for the lambda code zip file
    Type: String
    Default: lambda_function.zip
  LambdaVersion:
    Description: The S3 key for the lambda code zip file
    Type: String

Resources:
  
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: ParamS3Bucket
        S3Key:
          Ref: ParamS3Key
        S3ObjectVersion:
          Ref: LambdaVersion
      Description: Custom CloudFormation resoiurce to return the latest AMI with given
        search parameters
      Environment:
        Variables:
          SPLUN_HEC_TOKEN : 123456-abcdef-987654
          SPLUNK_HEC_URL : www.1234test.com
          index : api
      FunctionName:
        Fn::Sub: Lamda-${AWS::StackName}
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::260913995125:role/AMI-Search-testnew12
      Runtime: nodejs12.x
      Timeout: 60
Outputs:
  LambdaFunctionARN:
    Description: The ARN of the lambda function
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
